[project]
name = "ai-khrabrov"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "fastapi[standard]>=0.115.12",
    "langchain>=0.3.25",
    "requests>=2.32.3",
]
