[project]
name = "ragaik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.135.3",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.27",
    "langchain-huggingface>=1.2.1",
    "pandas>=3.0.2",
    "starlette>=1.0.0",
    "faiss-cpu>=1.9.0",
    "langgraph>=1.1.6",
    "langchain-openai>=1.1.12",
    "langgraph-checkpoint-redis>=0.4.0",
]
